Title: Python C API: Exception Handling Functions
URL: https://docs.python.org/3/c-api/exceptions.html
Summary: This section describes the functions `Py_ReprLeave` and `Py_ReprEnter`, detailing their use in handling Python exceptions at the C API level. It also lists global variables for standard Python exceptions, which are accessible as `PyExc_` followed by the respective Python exception name.
---

voidPy_ReprLeave([PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject "PyObject")*object)[¶](https://docs.python.org/3/c-api/exceptions.html#c.Py_ReprLeave "Link to this definition")
    _Part of the[ Stable ABI](https://docs.python.org/3/c-api/stable.html#stable)._
Ends a [`Py_ReprEnter()`](https://docs.python.org/3/c-api/exceptions.html#c.Py_ReprEnter "Py_ReprEnter"). Must be called once for each invocation of [`Py_ReprEnter()`](https://docs.python.org/3/c-api/exceptions.html#c.Py_ReprEnter "Py_ReprEnter") that returns zero.
## Standard Exceptions[¶](https://docs.python.org/3/c-api/exceptions.html#standard-exceptions "Link to this heading")
All standard Python exceptions are available as global variables whose names are `PyExc_` followed by the Python exception name. These have the type [PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject "PyObject")*; they are all class objects. For completeness, here are all the variables:
C Name | Python Name | Notes  
---|---|---  
`PyExc_BaseException` | [`BaseException`](https://docs.python.org/3/library/exceptions.html#BaseException "BaseException") | [[1]](https://docs.python.org/3/c-api/exceptions.html#id7)  
`PyExc_Exception` | [`Exception`](https://docs.python.org/3/library/exceptions.html#Exception "Exception") | [[1]](https://docs.python.org/3/c-api/exceptions.html#id7)  
`PyExc_ArithmeticError` | [`ArithmeticError`](https://docs.python.org/3/library/exceptions.html#ArithmeticError "ArithmeticError") | [[1]](https://docs.python.org/3/c-api/exceptions.html#id7)  
`PyExc_AssertionError` | [`AssertionError`](https://docs.python.org/3/library/exceptions.html#AssertionError "AssertionError") |   
`PyExc_AttributeError` | [`AttributeError`](https://docs.python.org/3/library/exceptions.html#AttributeError "AttributeError") |   
`PyExc_BlockingIOError` | [`BlockingIOError`](https://docs.python.org/3/library/exceptions.html#BlockingIOError "BlockingIOError") |   
`PyExc_BrokenPipeError` | [`BrokenPipeError`](https://docs.python.org/3/library/exceptions.html#BrokenPipeError "BrokenPipeError") |   
`PyExc_BufferError` | [`BufferError`](https://docs.python.org/3/library/exceptions.html#BufferError "BufferError") |   
`PyExc_ChildProcessError` | [`ChildProcessError`](https://docs.python.org/3/library/exceptions.html#ChildProcessError "ChildProcessError") |   
`PyExc_ConnectionAbortedError` | [`ConnectionAbortedError`](https://docs.python.org/3/library/exceptions.html#ConnectionAbortedError "ConnectionAbortedError") |   
`PyExc_ConnectionError` | [`ConnectionError`](https://docs.python.org/3/library/exceptions.html#ConnectionError "ConnectionError") |   
`PyExc_ConnectionRefusedError` | [`ConnectionRefusedError`](https://docs.python.org/3/library/exceptions.html#ConnectionRefusedError "ConnectionRefusedError") |   
`PyExc_ConnectionResetError` | [`ConnectionResetError`](https://docs.python.org/3/library/exceptions.html#ConnectionResetError "ConnectionResetError") |   
`PyExc_EOFError` | [`EOFError`](https://docs.python.org/3/library/exceptions.html#EOFError "EOFError") |   
`PyExc_FileExistsError` | [`FileExistsError`](https://docs.python.org/3/library/exceptions.html#FileExistsError "FileExistsError") |   
`PyExc_FileNotFoundError` | [`FileNotFoundError`](https://docs.python.org/3/library/exceptions.html#FileNotFoundError "FileNotFoundError") |   
`PyExc_FloatingPointError` | [`FloatingPointError`](https://docs.python.org/3/library/exceptions.html#FloatingPointError "FloatingPointError") |   
`PyExc_GeneratorExit` | [`GeneratorExit`](https://docs.python.org/3/library/exceptions.html#GeneratorExit "GeneratorExit") |   
`PyExc_ImportError` | [`ImportError`](https://docs.python.org/3/library/exceptions.html#ImportError "ImportError") |   
`PyExc_IndentationError` | [`IndentationError`](https://docs.python.org/3/library/exceptions.html#IndentationError "IndentationError") |   
`PyExc_IndexError` | [`IndexError`](https://docs.python.org/3/library/exceptions.html#IndexError "IndexError") |   
`PyExc_InterruptedError` | [`InterruptedError`](https://docs.python.org/3/library/exceptions.html#InterruptedError "InterruptedError") |   
`PyExc_IsADirectoryError` | [`IsADirectoryError`](https://docs.python.org/3/library/exceptions.html#IsADirectoryError "IsADirectoryError") |   
`PyExc_KeyError` | [`KeyError`](https://docs.python.org/3/library/exceptions.html#KeyError "KeyError") |   
`PyExc_KeyboardInterrupt` | [`KeyboardInterrupt`](https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt "KeyboardInterrupt") |   
`PyExc_LookupError` | [`LookupError`](https://docs.python.org/3/library/exceptions.html#LookupError "LookupError") | [[1]](https://docs.python.org/3/c-api/exceptions.html#id7)  
`PyExc_MemoryError` | [`MemoryError`](https://docs.python.org/3/library/exceptions.html#MemoryError "MemoryError") |   
`PyExc_ModuleNotFoundError` | [`ModuleNotFoundError`](https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError "ModuleNot