Title: Changelog: Bug Fixes and Patches
URL: https://docs.python.org/3/whatsnew/changelog.html
Summary: This section documents various bug fixes and patches in Python, addressing assertion failures in modules such as `json`, `ctypes`, and `_random`. Notable contributions include fixes for bad arguments and attributes that previously caused errors, with patches primarily by Oren Milman.
---

tion=redirect&bpo=31505): Fix an assertion failure in `json`, in case `_json.make_encoder()` received a bad `encoder()` argument. Patch by Oren Milman.
  * [bpo-31492](https://bugs.python.org/issue?@action=redirect&bpo=31492): Fix assertion failures in case of failing to import from a module with a bad `__name__` attribute, and in case of failing to access an attribute of such a module. Patch by Oren Milman.
  * [bpo-31490](https://bugs.python.org/issue?@action=redirect&bpo=31490): Fix an assertion failure in `ctypes` class definition, in case the class has an attribute whose name is specified in `_anonymous_` but not in `_fields_`. Patch by Oren Milman.
  * [bpo-31478](https://bugs.python.org/issue?@action=redirect&bpo=31478): Fix an assertion failure in `_random.Random.seed()` in case the argument has a bad `__abs__()` method. Patch by Oren Milman.
  * [bpo-31315](https://bugs.python.org/issue?@action=redirect&bpo=31315): Fix an assertion failure in imp.create_dynamic(), when spec.name is not a string. Patch by Oren Milman.
  * [bpo-31311](https://bugs.python.org/issue?@action=redirect&bpo=31311): Fix a crash in the `__setstate__()` method of `ctypes._CData`, in case of a bad `__dict__`. Patch by Oren Milman.
  * [bpo-31293](https://bugs.python.org/issue?@action=redirect&bpo=31293): Fix crashes in true division and multiplication of a timedelta object by a float with a bad as_integer_ratio() method. Patch by Oren Milman.
  * [bpo-31285](https://bugs.python.org/issue?@action=redirect&bpo=31285): Fix an assertion failure in `warnings.warn_explicit`, when the return value of the received loaderâ€™s `get_source()` has a bad `splitlines()` method. Patch by Oren Milman.
  * [bpo-30817](https://bugs.python.org/issue?@action=redirect&bpo=30817): `PyErr_PrintEx()` clears now the ignored exception that may be raised by `_PySys_SetObjectId()`, for example when no memory.